server:
  port: 8060

spring:
  application:
    name: notification_micro_service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: local-vh
  mail:
    host: 127.0.0.1
    port: 1025

user:
  queue:
    create: create-queue

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}