server:
  port: 8050
  name: Ms Funcionario

spring:
  application:
    name: employee_micro_service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/employee?retryWrites=true&w=majority
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: local-vh
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /user-api-docs.html
  paths-to-match: /**/user/**

eldorado:
  jwt:
    secret: KaPdRgUkXp2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D
    expirationMs: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
