server:
  port: 8761

eureka:
  instance: ms-eureka-discovery
  client:
     register-with-eureka: false
     fetch-registry: false
spring:
  application:
    name: ms-discovery
    service-url:
      defaultZone: http://localhost:8761/eureka

